/* DO NOT EDIT THIS FILE - it is machine generated */


#include "com_dyhdyh_ffmpeg_FFmpegJNI.h"
#include <jni.h>
#include <android/log.h>

#ifndef _Included_com_dyhdyh_ffmpeg_FFmpegJNI
#define _Included_com_dyhdyh_ffmpeg_FFmpegJNI
#ifdef __cplusplus
extern "C"
{
#endif

#include "ffmpeg.h"

#ifdef __cplusplus
}
#endif
#endif
extern "C" int run(int argc, char **argv);

JNIEXPORT jint JNICALL Java_com_dyhdyh_ffmpeg_FFmpegJNI_nativeExec
        (JNIEnv *env, jclass jcls, jobjectArray commands, jobject progressListener,
         jobject loggerListener) {

    /*jclass clazz = env->GetObjectClass( progressListener);
    if (clazz != NULL) {
        jmethodID onProgressID = env->GetMethodID( clazz, "onProgress", "(F)V");
        if (onProgressID != NULL) {
            jfloat p = 0;
            env->CallVoidMethod( progressListener, onProgressID, p);
        }
    }*/

    int argc = env->GetArrayLength(commands);
    char *argv[argc];

    int i;
    for (i = 0; i < argc; i++) {
        jstring js = (jstring) env->GetObjectArrayElement(commands, i);
        argv[i] = (char *) env->GetStringUTFChars(js, 0);
    }
    return run(argc, argv);
}