/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dyhdyh_ffmpeg_FFmpegJNI */

#ifndef _Included_com_dyhdyh_ffmpeg_FFmpegJNI
#define _Included_com_dyhdyh_ffmpeg_FFmpegJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dyhdyh_ffmpeg_FFmpegJNI
 * Method:    nativeExec
 * Signature: ([Ljava/lang/String;Lcom/dyhdyh/ffmpeg/OnFFmpegProgressListener;)I
 */
JNIEXPORT jint JNICALL Java_com_dyhdyh_ffmpeg_FFmpegJNI_nativeExec
        (JNIEnv *, jclass, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
