/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dyhdyh_ffmpegjni_FFmpegJNI */

#ifndef _Included_com_dyhdyh_ffmpegjni_FFmpegJNI
#define _Included_com_dyhdyh_ffmpegjni_FFmpegJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dyhdyh_ffmpegjni_FFmpegJNI
 * Method:    nativeExec
 * Signature: ([Ljava/lang/String;Lcom/dyhdyh/ffmpegjni/OnFFmpegProgressListener;)I
 */
JNIEXPORT jint JNICALL Java_com_dyhdyh_ffmpegjni_FFmpegJNI_nativeExec
        (JNIEnv *, jclass, jobjectArray, jboolean);

JNIEXPORT jstring JNICALL
Java_com_dyhdyh_ffmpegjni_FFmpegJNI_avcodecInfo(JNIEnv *, jclass);

JNIEXPORT jstring JNICALL
Java_com_dyhdyh_ffmpegjni_FFmpegJNI_avformatInfo(JNIEnv *, jclass);

JNIEXPORT jstring JNICALL
Java_com_dyhdyh_ffmpegjni_FFmpegJNI_avfilterInfo(JNIEnv *, jclass);

JNIEXPORT jstring JNICALL
Java_com_dyhdyh_ffmpegjni_FFmpegJNI_configurationInfo(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
