/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dyhdyh_ffmpegjni_FFmpegJNI */

#ifndef _Included_com_dyhdyh_ffmpegjni_FFmpegJNI
#define _Included_com_dyhdyh_ffmpegjni_FFmpegJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dyhdyh_ffmpegjni_FFmpegJNI
 * Method:    nativeExec
 * Signature: ([Ljava/lang/String;Lcom/dyhdyh/ffmpegjni/OnFFmpegProgressListener;)I
 */
JNIEXPORT jint JNICALL Java_com_dyhdyh_ffmpegjni_FFmpegJNI_nativeExec
        (JNIEnv *, jclass, jobjectArray);

JNIEXPORT jstring JNICALL
Java_com_dyhdyh_ffmpegjni_FFmpegJNI_avcodecInfo(JNIEnv *, jclass);

JNIEXPORT jstring JNICALL
Java_com_dyhdyh_ffmpegjni_FFmpegJNI_avformatInfo(JNIEnv *, jclass);

JNIEXPORT jstring JNICALL
Java_com_dyhdyh_ffmpegjni_FFmpegJNI_avfilterInfo(JNIEnv *, jclass);

JNIEXPORT jstring JNICALL
Java_com_dyhdyh_ffmpegjni_FFmpegJNI_configurationInfo(JNIEnv *, jclass);

JNIEXPORT void JNICALL
Java_com_dyhdyh_ffmpegjni_FFmpegJNI_nativeSetLoggerListener(JNIEnv *, jclass, jobject);

JNIEXPORT void JNICALL
Java_com_dyhdyh_ffmpegjni_FFmpegJNI_nativeSetProgressListener(JNIEnv *, jclass, jobject);

JNIEXPORT void JNICALL
Java_com_dyhdyh_ffmpegjni_FFmpegJNI_nativeRelease(JNIEnv *, jclass);

void callback_java_progress(float progressMS);

void callback_java_log(int level, const char *message);


#ifdef __cplusplus
}
#endif
#endif
